apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-hkzvpxdo
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/backend-tests-go-hkzvpxdo:cd24d18da014c0e64c117022043b3b5d1be993b7@sha256:ebe9886a49482e83d4764550df668ee3f4dec8ff4008fcdd2bdbab488eabba6a
        name: container-image  
